### ISSUE TITLE
Determine how to extract HDFS Files for the Pilot Study

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-Docker#10]
The HDFS files need to be extracted from the containerized HDFS Cluster (volumes).

**Comment by afolarin** [comment]
see README c3b89b013e2558548890591de3031aaeb12ed069  dcompose-stack/radar-cp-hadoop-stack.

**Comment by blootsvoets** [comment]
Solved with c3b89b013e2558548890591de3031aaeb12ed069
