### ISSUE TITLE
Add NodeJS Container with RADAR Dashboard

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-Docker#11]
@kerzmaximilian @herkulano we need to have a container with the dashboard components, can you please provide the necessary Dockerfile for this or instructions for this component.

**Comment by kerzmaximilian** [comment]
Ill get on it

**Comment by herkulano** [comment]
@kerzmaximilian the current dockerised version uses [http-server](https://www.npmjs.com/package/http-server) to serve the static files. It might be improved with nginx instead.
