### ISSUE TITLE
How to manage secret parameters within docker

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Docker#19]
The easiest way is to use the combination of env variable and an env-file. Doing so, parameters will be provided at run time: no need to hardcode them inside the image. This approach does not work with certificates, in this case a volume may help.

An advanced alternative, that covers all possible scenarios and for this reason often used in production, is *Hashicorp Vault*. [Katacoda tutorial](https://www.katacoda.com/courses/docker-production/vault-secrets)

**Comment by afolarin** [comment]
thought not relevant unless we are using Swarm, there is secret management arriving in Docker 1.13 https://github.com/docker/docker/pull/27794

**Comment by afolarin** [comment]
@fnobilia close for now?

**Comment by blootsvoets** [comment]
FYI, in the hadoop stack, SMTP secrets are managed with an service-specific `smtp.env` file. Hadoop volume configuration (=machine-dependent) can be done in the global `.env` file.

**Comment by fnobilia** [comment]
MongoDb parameters are in `.env` file as well. But we cannot consider this approach safe since password is not encrypted. We can use the `.env`  but after staring up the platform we should remove the password.

**Comment by blootsvoets** [comment]
Could we move secrets to container-dedicated env files? And keep `.env` for non-secret configuration? Perhaps, like in the Kerberos package, make a `secrets` folder with all image `env` templates and `.gitignore`. I'd prefer not to remove secrets, because that would make something like Portainer unable to restart a stopped container.

**Comment by blootsvoets** [comment]
On the other hand: once a container is started, its configuration is visible in Portainer anyway, including `secrets`. A shared secrets data volume could work? We'd inject the data we need into the data volume with temporary docker commands, and mount the volume in the requested container. It would be quite some work... Note that if someone gets root access to our infrastructure, all our secrets are compromised anyway.

**Comment by fnobilia** [comment]
We need a workaround for the pilot only. In production maybe we will use docker swarm of some alternative and all of them should have a tool to mange secrets.
