### ISSUE TITLE
Explicitly move WIP stacks to a WIP directory

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-Docker#23]
The `radar-cp-stack` and `radar-cp-hadoop-stack` are now tested on Travis in the travis branch. For each stack, Travis tests whether its docker-compose files successfully starts all containers. The `sasl` and `swarm` stacks are not tested, because they are expected to fail. Can we move those to experimental or WIP? Once Docker 1.13 is released, the `radar-cp-swarm-stack` should hopefully be able to run on Travis.

**Comment by afolarin** [comment]
@blootsvoets makes sense, please move to `wip`.
