### ISSUE TITLE
install script breaks nginx.conf

### ISSUE THREAD

**Issue by sboettcher** [RADAR-CNS/RADAR-Docker#33]
current (9a5487ba65d84e1c1ffd7ad1db09831327f0c7a4) `install-radar-stack.sh` breaks `nginx.conf` server name, can for example be fixed by changing
```diff
-inline_variable 'server_name[[:space:]]*' $SERVER_NAME etc/nginx.conf
+inline_variable 'server_name[[:space:]]*' "$SERVER_NAME;" etc/nginx.conf
```

edit: breaks is a strong word, it produces a warning...
```
nginx: [warn] server name "/var/log/nginx/access.log" has suspicious symbols in /etc/nginx/nginx.conf:19
```

**Comment by blootsvoets** [comment]
Thanks for reporting this, fixed now.
