### ISSUE TITLE
Additional RADAR components

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-Docker#5]
Compose containers to be added:

Requirements for Pilot Project No1:
- [x] HDFS (Jan 2017)
- [x] Nodejs
- [x] MongoDB
- [x] Tomcat REST-API
- [x] Backend: Kafka-HDFS connector
- [x] Backend: Kafka-MongoDB connector
- [x] Backend: E4 streams

Security Components: 
- [x] HTTP proxy
- [x] SSO component

Local Timeserver (for pilot studies) is easier to deploy as a system package, as it needs to modify the system time.

**Comment by blootsvoets** [comment]
@nivemaham is currently making RADAR-Backend docker images.
