### ISSUE TITLE
redcap-config-listener broken on mac

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-Docker#58]
On macOS, redcap-config-listener gives an error. Starting it as a background process is also quite brittle (it will break with ssh + logging out), implementing it as a system service would be preferable. Alternatively, a restart can be manually triggered after editing configuration files, which would be more transparent.

**Comment by yatharthranjan** [comment]
@blootsvoets agreed. This was required when the MP configuration for redcap integration was based on project ID. But now, since the configuration is based on name of the project which we can know in advance, I think there is no immediate need for this anymore. Should I remove it from the stack?

**Comment by blootsvoets** [comment]
Yes please!

**Comment by yatharthranjan** [comment]
Closed with #63
