### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Docker#6]
We need to monitor the docker cluster. Different solutions are currently available to monitor **docker containers** and the **applications** running inside them. The most used are:

- [graylog](https://www.graylog.org/features) 
- [fluentd](http://www.fluentd.org/architecture) 
- [logstash](https://www.elastic.co/products/logstash) 

All of them are supported by docker out-of-the-box ([Docker doc](https://docs.docker.com/engine/admin/logging/overview/)).

While the first one is an all-in-one solution: it provides ingestion, visualisation, rest api and alerts. The other two have to be coupled with a storage component, to persist the informations (e.g. Elasticsearch), and a visualisation tool (e.g. Kibana).

For more details check

- [Logstash + Elasticsearch + Kibana](https://www.elastic.co/products)
- [Fluentd + Elasticsearch + Kibana](https://www.digitalocean.com/community/tutorials/elasticsearch-fluentd-and-kibana-open-source-log-search-and-visualization)
- [Graylog (Elasticsearch + MongoDB) doc](http://docs.graylog.org/en/2.1/)

To monitor the **hardware** the best candidate is the Google [Cadvisor](https://github.com/google/cadvisor/blob/master/docs/api.md). It can be combined with [InfluxDB](https://www.influxdata.com/time-series-platform/influxdb/) and [Grafana](http://grafana.org) to persist and visualise data ([example](https://www.brianchristner.io/how-to-setup-docker-monitoring/)). Another solution is to use Cadvisor with [Prometheus](https://prometheus.io), a metrics system with dashboards and alerting capabilities ([ex1](https://stefanprodan.com/2016/a-monitoring-solution-for-docker-hosts-containers-and-containerized-services/) [ex2](https://www.brianchristner.io/how-to-setup-prometheus-docker-monitoring/)).

All these solutions are **open-source**.

**Comment by fnobilia** [comment]
[Portainer](http://portainer.io/overview.html): a dashboard for Docker

**Comment by afolarin** [comment]
closed by f6c569b8eb81c37171ea286a8429b2530359aef1

**Comment by afolarin** [comment]
Actually keep open (cadvisor and portainer) we still planned to add greylog.

**Comment by blootsvoets** [comment]
For the pilot, is portainer enough for logging? Each docker process can be selected and its logs viewed. For a distributed setup graylog may be better, but it also requires two additional services: mongodb and  elasticsearch.

**Comment by afolarin** [comment]
OK I just wasn't sure. I think the existing is fine monitoring is fine for the pilot study

**Comment by blootsvoets** [comment]
I've added a new docker-compose stack with graylog to dcompose-stack/logging. However, to use it, each docker container in a docker-compose file needs to use the following settings:
```yaml
logging:
  driver: gelf
  options:
    gelf-address: udp://localhost:12201
```
This will only work if the logging stack is actually running. Moreover, the logs will then no longer be collected locally, meaning they are no longer available through the console or through portainer. As long as we're doing single-host deployments, I suggest to leave the logging setup as-is. When we do plan to deploy in a multi-host setting, this logging solution ready to go, though.

**Comment by afolarin** [comment]
@blootsvoets agree on keeping local logging, but great that we can centralise when we need to :+1:
