### ISSUE TITLE
Handle incoming requests with OPTIONS method for MP

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-CNS/RADAR-Docker#65]
The POST or GET methods in most instances are preceeded by a pre-flight OPTIONS request to the server. The aRMT app was thus not able to access the token end-point of Management Portal because the OPTIONS method is forbidden with the following error message - 
```
polyfills.js:3 OPTIONS https://radar-cns-platform.rosalind.kcl.ac.uk//managementportal/oauth/token 403 (Forbidden)
(index):1 Failed to load https://radar-cns-platform.rosalind.kcl.ac.uk//managementportal/oauth/token: Response for preflight has invalid HTTP status code 403
```

This could probably be implemented as a conditional block in the nginx.conf file

**Comment by dennyverbeeck** [comment]
Apparently the default jHipster configuration enables CORS in the dev profile, but not in the prod profile, which i hadn't noticed. I will fix it on the MP side so that CORS works as it should without needing additional configuration of external components like a proxy. See [this PR](https://github.com/RADAR-CNS/ManagementPortal/pull/116).

**Comment by yatharthranjan** [comment]
Yes that would be best. The PR looks good. For now I will keep the nginx conf on the server till the new version of MP is released

**Comment by blootsvoets** [comment]
MP will only be accessible via nginx, so indeed CORS needs to be enabled there. Changing the settings in MP shouldn’t have an effect on clients.

**Comment by yatharthranjan** [comment]
@dennyverbeeck you already implemented this. Should we close this?

**Comment by dennyverbeeck** [comment]
I think we can, we should make sure though that the response headers from MP are being properly passed through to the client by nginx.

**Comment by yatharthranjan** [comment]
@dennyverbeeck Okay adding this to my to do list and closing the issue
