### ISSUE TITLE
Requesting SSL certificate does not work if too many certs already issued

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-CNS/RADAR-Docker#69]
if too many certs already issued we get the error - 
```
There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for exact set of domains: radar-backend.ddns.net
Please see the logfiles in /var/log/letsencrypt for more details.
touch: /etc/openssl/live/radar-backend.ddns.net/.letsencrypt: No such file or directory
```
Instead there should be a way to get the previously issued certificate if not found locally

**Comment by afolarin** [comment]
Ok I'll look into this.

**Comment by afolarin** [comment]
@yatharthranjan try again now.

looks like there is a 7 day delay imposed if you max out the allowance.
https://community.letsencrypt.org/t/there-were-too-many-reque9:24:09 sts-of-a-given-type-error-creating-new-cert-too-many-certificates-already-issued-for-exact-set-of-domains/39725

https://crt.sh/?q=radar-backend.ddns.net

**Comment by yatharthranjan** [comment]
Yes but the 7 days is not over yet. So I was thinking is there a way to retrieve the previously issued certificate that should work fine instead of trying to issue a new one. And I cannot open the first link, it says its private

**Comment by blootsvoets** [comment]
If you keep the `certs` and `certs-data` volumes, you won't have to request it that many times. As far as I understand all the information of the certificates is in there, there is no external party to retrieve the certs from. Alternatively, once you succeed, you could make a backup of those two volumes and restore the backup if the volumes are somehow lost.

**Comment by yatharthranjan** [comment]
Yes I guess it would be best to make a periodic backup of these using `rsync` because I did `docker volume prune` and lost the certs

**Comment by blootsvoets** [comment]
In #68 I've added a label `certs` to the `certs` volumes. Then you can run
```
docker volume prune --filter label!=certs
docker system prune --filter label!=certs
```
and the certificates will not be affected. We could think of more elaborate label schemes as well in the future.

**Comment by yatharthranjan** [comment]
@blootsvoets cool looks like a good solution. Also I will add a backup cron job which can be handy.

**Comment by afolarin** [comment]
@blootsvoets  the labelling is a good idea and I think this will do for now (should we alias the prune command to add the filter to reduce the labelled vols getting removed by accident?). 
This is fine, we can store this periodically, we can also add to wiki too if needed.
