### ISSUE TITLE
UnknownTopicOrPartitionException for _schemas

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Docker#7]
Upon start up sometimes at least one broker raises this error:
**ERROR [ReplicaFetcherThread-0-1], Error for partition [_schemas,0] to broker 1:org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition. (kafka.server.ReplicaFetcherThread)**

Modifying the containers dependences has mitigated the issue: now it appears sometimes, while before it was always raised.

**Comment by fnobilia** [comment]
The issue has been solved by 4bf345f. But now the schema-registry points a single Zookeeper instance instead of the entire Zookeeper cluster. For this reasons I leave the issue open.

**Comment by fnobilia** [comment]
Open a [post](https://groups.google.com/forum/#!topic/confluent-platform/CqStdnLQfB0) on Confluent Google Group about this issue

**Comment by afolarin** [comment]
Which version of Zookeeper are we using?
see
> The reason is mostly due to the way clusters are configured. Indeed, in Zookeeper’s case, each instance must be statically identified within the cluster.

http://www.defuze.org/archives/351-running-a-zookeeper-and-kafka-cluster-with-kubernetes-on-aws.html

**Comment by afolarin** [comment]
`# echo envi | nc 127.0.0.1 22181`
Environment:
zookeeper.version=**3.4.8--1**, built on 02/06/2016 03:18 GMT

Seems ZK cluster is ok.
Verify that ZK ensemble is ready

```
for i in 22181 32181 42181; do
   docker run --net=host --rm confluentinc/cp-zookeeper:3.0.0 bash -c "echo stat | nc localhost $i | grep Mode"
done
```

Mode: follower
Mode: follower
Mode: leader


`docker run --net=host --rm confluentinc/cp-kafka:3.1.1 kafka-topics --describe --topic bar --zookeeper localhost:32181`
Topic:bar	PartitionCount:3	ReplicationFactor:3	Configs:
	Topic: bar	Partition: 0	Leader: 2	Replicas: 2,3,1	Isr: 2,3,1
	Topic: bar	Partition: 1	Leader: 3	Replicas: 3,1,2	Isr: 3,1,2
	Topic: bar	Partition: 2	Leader: 1	Replicas: 1,2,3	Isr: 1,2,3

**Comment by afolarin** [comment]
closing as not an issue for immediate task and likely the version of ZK will be moved up by the time we need to look at ZK clustering.
