### ISSUE TITLE
Check-health.sh does not work with crontab

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-CNS/RADAR-Docker#89]
The check-health.sh file right now does not work with crontab because it uses relative paths for util.sh,.env and docker-compose.yml files. We should update these to absolute so that its works with crontab

**Comment by blootsvoets** [comment]
Note that when installing it as a systemd unit, you can set the working directory. Perhaps we can add some systemd timers for common functionalities like these and renewing the SSL certificate.

**Comment by yatharthranjan** [comment]
Okay thanks. I was only trying to install it as a cron job. Will try the systemd now. Thanks
